title: Vasanth V
description: A place where I write junk, chase random thoughts, and try to make sense of my chaotically organized brain. Keeping things simple & stupid.
url: https://vasanthv.github.io
markdown: kramdown

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:name/

feed:
  collections:
    - articles
  sort_by: "date"
  order: "descending"
